---
language: node_js

node_js:
  - stable

script:
- |
  sudo apt update
  sudo apt -y install gcc make automake autoconf git
  git clone -b master https://github.com/Dreamacro/clash-dashboard
  cd clash-dashboard
  npm install
  npm run build
  mkdir -p ../pages-dir
  mv dist ../pages-dir/clash
  echo 'm.mixhub.cn' > ../pages-dir/CNAME

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: pages-dir
  on:
    branch: dev

notifications:
  email: false
