---
language: node_js

node_js:
  - stable

script:
- |
  sudo apt update
  sudo apt -y install gcc make automake autoconf git
  git clone -b master https://github.com/Dreamacro/clash-dashboard
  cd clash-dashboard
  npm install
  npm run build
  sed -i 's#"//"#"http://"#g' dist/js/bundle.*.js # workaround to for https site fetch http XHR on 127.0.0.1
  mkdir -p ../pages-dir
  mv dist ../pages-dir/clash
  echo 'm.mixhub.cn' > ../pages-dir/CNAME

- |
  nvm install 6.14
  nvm use 6.14
  git clone https://github.com/mayswind/AriaNg
  cd AriaNg
  npm install
  gulp clean build
  mkdir -p ../pages-dir
  mv dist ../pages-dir/ariang

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: pages-dir
  on:
    branch: dev

notifications:
  email: false
